// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ4VrDVm45C8DREfRAuy1yph4DzOX8h9w',
    appId: '1:954743710308:web:92907f67953ccbfa927571',
    messagingSenderId: '954743710308',
    projectId: 'vibe-f9a3e',
    authDomain: 'vibe-f9a3e.firebaseapp.com',
    storageBucket: 'vibe-f9a3e.appspot.com',
    measurementId: 'G-1BVH2E23HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkjEtsBPeK_cYg4T-RdhAQP0wRGBfab_o',
    appId: '1:954743710308:android:3bc03a6f547ea23c927571',
    messagingSenderId: '954743710308',
    projectId: 'vibe-f9a3e',
    storageBucket: 'vibe-f9a3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgPhJIT4OKcrXPshof5J0dsO18yk_JPbs',
    appId: '1:954743710308:ios:b2fa1b1069c82cbd927571',
    messagingSenderId: '954743710308',
    projectId: 'vibe-f9a3e',
    storageBucket: 'vibe-f9a3e.appspot.com',
    iosBundleId: 'com.nosh.vibe',
  );
}
